In [30]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
df=pd.read_csv('teleCust1000t.csv')
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [49]:
x=np.array(df.drop(['custcat'],1))
y=np.array(df['custcat'])
x[0:5],y[0:5]

(array([[  2.,  13.,  44.,   1.,   9.,  64.,   4.,   5.,   0.,   0.,   2.],
        [  3.,  11.,  33.,   1.,   7., 136.,   5.,   5.,   0.,   0.,   6.],
        [  3.,  68.,  52.,   1.,  24., 116.,   1.,  29.,   0.,   1.,   2.],
        [  2.,  33.,  33.,   0.,  12.,  33.,   2.,   0.,   0.,   1.,   1.],
        [  2.,  23.,  30.,   1.,   9.,  30.,   1.,   2.,   0.,   0.,   4.]]),
 array([1, 4, 3, 1, 3], dtype=int64))

In [50]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))
x[0:5]

array([[-0.02696767, -1.055125  ,  0.18450456,  1.0100505 , -0.25303431,
        -0.12650641,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817,
        -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243,  1.0100505 , -0.4514148 ,
         0.54644972,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817,
         2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601,  1.0100505 ,  1.23481934,
         0.35951747, -1.36767088,  1.78752803, -0.22207644,  0.96655883,
        -0.23065004],
       [-0.02696767, -0.11831864, -0.69181243, -0.9900495 ,  0.04453642,
        -0.41625141, -0.54919639, -1.09029981, -0.22207644,  0.96655883,
        -0.92747794],
       [-0.02696767, -0.58672182, -0.93080797,  1.0100505 , -0.25303431,
        -0.44429125, -1.36767088, -0.89182893, -0.22207644, -1.03459817,
         1.16300577]])

In [61]:

from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split( x, y, test_size=0.2)
print ('Train set:', train_x.shape, train_y.shape)
print ('Test set:', test_x.shape,  test_y.shape)



Train set: (800, 11) (800,)
Test set: (200, 11) (200,)


In [54]:
from sklearn import neighbors


In [62]:
k=4
k_nearst=neighbors.KNeighborsClassifier(n_neighbors=k)
k_nearst.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=4)

In [66]:
y_predict = k_nearst.predict(test_x)
y_predict[0:5]

array([4, 2, 1, 3, 3], dtype=int64)

In [71]:
from sklearn import metrics
print("train accuracy :", metrics.accuracy_score(train_y,k_nearst.predict(train_x)))
print("test-accuracy:",metrics.accuracy_score(test_y,y_predict))

train accuracy : 0.5725
test-accuracy: 0.265
